-- vim.opt.rtp:prepend("/Users/ammsiss/Projects/filetree.nvim")

require("filetree")

-- Hello!

-- local function add_git_data(output)
--
--     local result = vim.system({ "git", "status", "--porcelain", "--ignored" }, { text = true }):wait()
--     local git_output = vim.split(result.stdout, "\n", { trimempty = true })
--     local git_root = vim.trim(vim.system({ "git", "rev-parse", "--show-toplevel" }, { text = true }):wait().stdout)
--
--     for _, git_line in ipairs(git_output) do
--
--         if git_line:match("fatal") then
--             break
--         end
--
--         local path = git_line:sub(4)
--         local node_path = git_root .. "/" .. path
--         local nodes = vim.split(path, "/")
--
--         for _, line in ipairs(output.lines) do
--
--             -- handle all files and directories at end of node list
--             for _, node in ipairs(nodes) do
--                 -- if line.path == node_path then
--                 --     print("line " .. line.path)
--                 --     print("node " .. node_path)
--                 -- end
--                 if line.path == node_path then
--                     if git_line:match("^ M ") then
--                         line.git_status = "TreeGitModified"
--                     elseif git_line:match("^!! ") then
--                         line.git_status = "TreeGitIgnored"
--                     elseif git_line:match("^%?%? ") then
--                         line.git_status = "TreeGitUntracked"
--                     elseif git_line:match("^A  ") then
--                         line.git_status = "TreeGitAdded"
--                     end
--                 -- handle directories not at end of node list
--                 elseif line.type == "directory" and line.name == node then
--                     if git_line:match("^ M ") then
--                         line.git_status = "TreeGitModified"
--                     end
--                 end
--             end
--         end
--     end
-- end

-- if line.git_status ~= nil then
--     vim.hl.range(
--         buf.num, ns, line.git_status,
--         ---@diagnostic disable-next-line: param-type-mismatch
--         { (i + 1) - 1, vim.str_byteindex(line.text, 3, false) },
--         { (i + 1) - 1, -1 }
--     )
-- end
--
-- if ignored then
--     if line.git_status ~= nil then
--         if line.git_status == "TreeGitIgnored" then
--             goto continue
--         end
--     end
-- end
--
--
-- vim.cmd("highlight TreeGitModified guifg=#fabd2f")
-- vim.cmd("highlight TreeGitUntracked guifg=#fb4934")
-- vim.cmd("highlight TreeGitAdded guifg=#b8bb26")
-- vim.cmd("highlight TreeGitIgnored guifg=#5c6370")
